// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0krtWn7z8P5itadZ8wa7ul2afEGGGs_w',
    appId: '1:544912086:web:a109a2685c65427925cf77',
    messagingSenderId: '544912086',
    projectId: 'classtech-72e27',
    authDomain: 'classtech-72e27.firebaseapp.com',
    storageBucket: 'classtech-72e27.firebasestorage.app',
    measurementId: 'G-LG5HN54GQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-TXCXFiUHMOmmQO9snzKitrxnb90Vbrs',
    appId: '1:544912086:android:bbbb4216b273a16d25cf77',
    messagingSenderId: '544912086',
    projectId: 'classtech-72e27',
    storageBucket: 'classtech-72e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBgGHxi0QvnfIwffBzSNVkTV8qP-CpBM',
    appId: '1:544912086:ios:016e71bc8a72cfd225cf77',
    messagingSenderId: '544912086',
    projectId: 'classtech-72e27',
    storageBucket: 'classtech-72e27.firebasestorage.app',
    iosBundleId: 'com.example.schoolParentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxBgGHxi0QvnfIwffBzSNVkTV8qP-CpBM',
    appId: '1:544912086:ios:016e71bc8a72cfd225cf77',
    messagingSenderId: '544912086',
    projectId: 'classtech-72e27',
    storageBucket: 'classtech-72e27.firebasestorage.app',
    iosBundleId: 'com.example.schoolParentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0krtWn7z8P5itadZ8wa7ul2afEGGGs_w',
    appId: '1:544912086:web:a314a037f04c8e4925cf77',
    messagingSenderId: '544912086',
    projectId: 'classtech-72e27',
    authDomain: 'classtech-72e27.firebaseapp.com',
    storageBucket: 'classtech-72e27.firebasestorage.app',
    measurementId: 'G-W4Q98HGESV',
  );
}
